### ISSUE TITLE
XML error when uploading

### ISSUE THREAD

**Issue by binyominzeev** [TheMengzor/youtube-upload#6]
Hi, I tried to install youtube-upload, the upload script failed quite strangely, with such an output:

```
running install
running build
running build_py
running build_scripts
error: file '/home/bz/yt-upload/bin/youtube-upload' does not exist
```

Afterwards, I used the ``youtube_upload.py`` script, with the suggested parameters to upload (without install procedure), and got the following output:

```
bz@bz-HP-Laptop-15-bs1xx:~$ youtube-upload --private --email=s********m --password '********' --title "Test" --category=People 20201204.webm 
Login to Youtube API: email='s********m', password='********'
Traceback (most recent call last):
  File "./youtube-upload", line 496, in <module>
    sys.exit(catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "./youtube-upload", line 109, in catch_exceptions
    fun(*args, **kwargs)
  File "./youtube-upload", line 493, in main
    run_main(parser, options, args)
  File "./youtube-upload", line 447, in run_main
    url = upload_video(youtube, options, video_path, len(args), index)
  File "./youtube-upload", line 361, in upload_video
    data = youtube.get_upload_form_data(*args, **kwargs)
  File "./youtube-upload", line 194, in get_upload_form_data
    entry = self._create_video_entry(*args, **kwargs)
  File "./youtube-upload", line 261, in _create_video_entry
    self.categories = self.get_categories()
  File "./youtube-upload", line 296, in get_categories
    xml = ElementTree.XML(xmldata)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 2, column 11
```

Is there a way to make it work? Thank you very much!

**Comment by binyominzeev** [comment]
Problem found, on line 214:

CATEGORIES_SCHEME = "http://gdata.youtube.com/schemas/2007/categories.cat"

This is referring to a 404 file, since the old YouTube API was disabled.

**Comment by mikepspc** [comment]
@binyominzeev Any tips on how to overcome this?

**Comment by binyominzeev** [comment]
Yes! This API is not supported anymore, so either use the updated one, for example with this script:

https://github.com/tokland/youtube-upload

But this involves an approvation procedure from Google which takes about 1-2 weeks and much effort.

Or use an alternative solution based on Selenium:

https://pypi.org/project/youtube-uploader-selenium/
https://github.com/tolgaouz/youtube-auto-upload

My opinion is that this latter is more flexible.
